### ISSUE TITLE
AttributeError when using Django 1.8 (  'module' object has no attribute 'commit_on_success' )

### ISSUE THREAD

**Issue by yogesh-** [divio/django-shop#293]
when I run ./manage.py runserver or ./manage.py migrate with django 1.8 and python2.7 it raises an exception and exits.

What i am missing ?

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/yogesh/base_store/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/yogesh/base_store/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
    django.setup()
  File "/home/yogesh/base_store/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/yogesh/base_store/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/yogesh/base_store/local/lib/python2.7/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/yogesh/base_store/local/lib/python2.7/site-packages/shop/models/__init__.py", line 4, in <module>
    from ordermodel import *  # NOQA
  File "/home/yogesh/base_store/local/lib/python2.7/site-packages/shop/models/ordermodel.py", line 8, in <module>
    from shop.models.productmodel import Product
  File "/home/yogesh/base_store/local/lib/python2.7/site-packages/shop/models/productmodel.py", line 15, in <module>
    Product = load_class(PRODUCT_MODEL, 'SHOP_PRODUCT_MODEL')
  File "/home/yogesh/base_store/local/lib/python2.7/site-packages/shop/util/loader.py", line 43, in load_class
    mod = import_module(class_module)
  File "/home/yogesh/base_store/local/lib/python2.7/site-packages/django/utils/importlib.py", line 45, in import_module
    __import__(name)
  File "/home/yogesh/base_store/local/lib/python2.7/site-packages/shop/models/defaults/product.py", line 4, in <module>
    from shop.models_bases.managers import (
  File "/home/yogesh/base_store/local/lib/python2.7/site-packages/shop/models_bases/managers.py", line 59, in <module>
    class OrderManager(models.Manager):
  File "/home/yogesh/base_store/local/lib/python2.7/site-packages/shop/models_bases/managers.py", line 93, in OrderManager

Unhandled exception in thread started by <function wrapper at 0x7fec3a7572a8>
Traceback (most recent call last):
  File "/home/yogesh/base_store/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 229, in wrapper
    fn(*args, **kwargs)
  File "/home/yogesh/base_store/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 107, in inner_run
    autoreload.raise_last_exception()
  File "/home/yogesh/base_store/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 252, in raise_last_exception
    six.reraise(*_exception)
  File "/home/yogesh/base_store/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 229, in wrapper
    fn(*args, **kwargs)
  File "/home/yogesh/base_store/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/yogesh/base_store/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/yogesh/base_store/local/lib/python2.7/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/yogesh/base_store/local/lib/python2.7/site-packages/shop/models/__init__.py", line 4, in <module>
    from ordermodel import *  # NOQA
  File "/home/yogesh/base_store/local/lib/python2.7/site-packages/shop/models/ordermodel.py", line 8, in <module>
    from shop.models.productmodel import Product
  File "/home/yogesh/base_store/local/lib/python2.7/site-packages/shop/models/productmodel.py", line 15, in <module>
    Product = load_class(PRODUCT_MODEL, 'SHOP_PRODUCT_MODEL')
  File "/home/yogesh/base_store/local/lib/python2.7/site-packages/shop/util/loader.py", line 43, in load_class
    mod = import_module(class_module)
  File "/home/yogesh/base_store/local/lib/python2.7/site-packages/django/utils/importlib.py", line 45, in import_module
    __import__(name)
  File "/home/yogesh/base_store/local/lib/python2.7/site-packages/shop/models/defaults/product.py", line 4, in <module>
    from shop.models_bases.managers import (
  File "/home/yogesh/base_store/local/lib/python2.7/site-packages/shop/models_bases/managers.py", line 59, in <module>
    class OrderManager(models.Manager):
  File "/home/yogesh/base_store/local/lib/python2.7/site-packages/shop/models_bases/managers.py", line 93, in OrderManager
    @transaction.commit_on_success
AttributeError: 'module' object has no attribute 'commit_on_success'

**Comment by atheiste** [comment]
Hi,
commit_on_success doesn’t exist in django 1.8 anymore. It was replaced by atomic.

Cheers,
Tomas

**Comment by yogesh-** [comment]
What should i exactly do to get rid of this error and move ahead ?

**Comment by atheiste** [comment]
I'd suggest to use some up to date branch of django-shop. You can use jrief's branch https://github.com/jrief/django-shop which is heavily updated and I believe brand new or you can use mine which is stabilised and just a bit different than the original.

**Comment by yogesh-** [comment]
Thanks @atheiste
